description: Cloud-edge collaborative online learning

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itplabrr1cl1
  vc: resrchvc

environment:
  image: aerysnan/kdva:latest

code:
  local_dir: $CONFIG_DIR

data:
  local_dir: ~/dataset/nydata
  remote_dir: dataset/KDVA/nydata

jobs:
- name: kdva_train_test_t0.4
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets ut_1 \
    --resutl-template {}.r.pkl \
    --anno-threshold 0.4 \
    --n-window 30 \
    --train-rate 1 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25 30
- name: kdva_train_test_t0.5
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets ut_1 \
    --resutl-template {}.r.pkl \
    --anno-threshold 0.5 \
    --n-window 30 \
    --train-rate 1 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25 30
- name: kdva_train_test_t0.6
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets ut_1 \
    --resutl-template {}.r.pkl \
    --anno-threshold 0.6 \
    --n-window 30 \
    --train-rate 1 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25 30

