description: Cloud-edge collaborative online learning

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itplabrr1cl1
  vc: resrchvc

environment:
  image: aerysnan/kdva:latest

code:
  local_dir: $CONFIG_DIR

data:
  local_dir: ~/dataset/nydata
  remote_dir: dataset/KDVA/nydata

jobs:
- name: train_1_fps
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets detrac_1 detrac_2 detrac_3 detrac_4 detrac_5 detrac_6 \
    --result-template {}.r.pkl \
    --anno-threshold 0.5 \
    --n-window 8 \
    --train-rate 1 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd_base.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25

- name: train_2_fps
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets detrac_1 detrac_2 detrac_3 detrac_4 detrac_5 detrac_6 \
    --result-template {}.r.pkl \
    --anno-threshold 0.5 \
    --n-window 8 \
    --train-rate 2 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd_base.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25

- name: train_3_fps
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets detrac_1 detrac_2 detrac_3 detrac_4 detrac_5 detrac_6 \
    --result-template {}.r.pkl \
    --anno-threshold 0.5 \
    --n-window 8 \
    --train-rate 3 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd_base.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25

- name: train_4_fps
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets detrac_1 detrac_2 detrac_3 detrac_4 detrac_5 detrac_6 \
    --result-template {}.r.pkl \
    --anno-threshold 0.5 \
    --n-window 8 \
    --train-rate 4 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd_base.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25

- name: train_5_fps
  sku: G1
  command:
  - python tools/full_pipeline.py \
    --datasets detrac_1 detrac_2 detrac_3 detrac_4 detrac_5 detrac_6 \
    --result-template {}.r.pkl \
    --anno-threshold 0.5 \
    --n-window 8 \
    --train-rate 5 \
    --val-rate 0.1 \
    --cfg configs/custom/ssd_base.py \
    --eval-template {}.eval.pkl \
    --n-process 4 \
    --framerates 5 10 15 20 25