description: Cloud-edge collaborative online learning

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itplabrr1cl1
  vc: resrchvc

environment:
  image: aerysnan/kdva:latest

code:
  local_dir: $CONFIG_DIR

data:
  local_dir: ~/dataset/nydata
  remote_dir: dataset/KDVA/nydata

jobs:
- name: kdva_train_test_t0.4
  sku: G1
  command:
  - python train_test_na.py -d ut_1 -t 0.4
- name: kdva_train_test_t0.5
  sku: G1
  command:
  - python train_test_na.py -d ut_1 -t 0.5
- name: kdva_train_test_t0.6
  sku: G1
  command:
  - python train_test_na.py -d ut_1 -t 0.6
