description: Cloud-edge collaborative online learning
environment:
  image: aerysnan/kdva:latest

code:
  local_dir: $CONFIG_DIR

data:
  local_dir: nydata

jobs:
- name: train_test_t0.4
  sku: G1
  command:
  - python train_test_na.py -d ut_1 -r 1 -t 0.4
- name: train_test_t0.5
  sku: G1
  command:
  - python train_test_na.py -d ut_1 -r 1 -t 0.5
- name: train_test_t0.6
  sku: G1
  command:
  - python train_test_na.py -d ut_1 -r 1 -t 0.6
