version: "3.9"  # optional since v1.27.0
services:

  source:
    build: ./src/cmd/source
    volumes:
      - ${AMLT_DATA_DIR}:/data
    command: /source --id 1 --dataset detrac_1 --dir /data --edge localhost:8080 --debug
    depends_on:
      - edge

  edge:
    build: ./src/cmd/edge
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/cfg_arch.json:/cfg.json
    command: /edge --id 1 --port 8080 --dir /dump --config /cfg.json --worker localhost:8081 --cloud localhost:8083 --debug
    depends_on:
      - cloud
      - worker


  cloud:
    build: ./src/cmd/cloud
    ports:
      - 8083:8083
    volumes:
      - ${PWD}/cfg_arch.json:/cfg.json
    command: /cloud --port 8082 --work-dir /dump --config /cfg.json --trainer localhost:8082 --debug
    depends_on:
      - trainer

  worker:
    build: ./src/worker
    ports:
      - 8081:8081
    volumes: 
      - ${PWD}/configs:/configs
      - ${AMLT_DATA_DIR}:/data
    command: python main.py --config /configs/custom/ssd_base.py --checkpoint /data/models/ssd.pth --port 8081 --device cuda:0
    runtime: nvidia

  trainer:
    build: ./src/trainer
    ports:
      - 8082:8082
    volumes: 
      - ${PWD}/configs:/configs
      - ${PWD}/cfg_arch.json:/cfg_emu.json
      - ${AMLT_DATA_DIR}:/data
    command: python main.py --teacher-config /configs/custom/rcnn_base.py --student-config /configs/custom/ssd_base.py --teacher-checkpoint /data/models/r101.pth --student-checkpoint /data/models/ssd.pth --emulation-config /cfg_emu.json --device cuda:1 --port 8082
    runtime: nvidia
